# Site settings
title: "NHibernate"
email: "" 
description: "The official NHibernate community site. Download NHibernate. Read blogs. Contribute to the NHibernate Wiki. Find reference documentation."
baseurl: "" 
url: "http://nhibernate.github.io"
twitter_username: nhibernate
github_username:  nhibernate
timezone: 'GMT-03:00'

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
#  - jekyll-archives
